"""separate_schedule_type_and_config

Revision ID: eb89cf1bd63d
Revises: 1473f06d1455
Create Date: 2025-09-29 18:34:56.661628

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'eb89cf1bd63d'
down_revision: Union[str, Sequence[str], None] = '1473f06d1455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop APScheduler table if it exists (may have been dropped in earlier migration)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'apscheduler_jobs' in inspector.get_table_names():
        op.drop_index(op.f('ix_apscheduler_jobs_next_run_time'), table_name='apscheduler_jobs')
        op.drop_table('apscheduler_jobs')

    op.drop_index(op.f('ix_scheduled_tasks_conversation_id'), table_name='scheduled_tasks')
    op.drop_index(op.f('ix_scheduled_tasks_job_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('agent_instructions', sa.TEXT(), nullable=False),
    sa.Column('schedule_config', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('failure_count', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('interactive', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('last_run', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    op.create_index(op.f('ix_scheduled_tasks_job_id'), 'scheduled_tasks', ['job_id'], unique=1)
    op.create_index(op.f('ix_scheduled_tasks_conversation_id'), 'scheduled_tasks', ['conversation_id'], unique=False)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apscheduler_jobs_next_run_time'), 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
